server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb+srv://user:IxO6P8P1tQIysp3t@cluster0.vl1uzvv.mongodb.net/tripdiary_destination_db?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
